project:
  type: book
  output-dir: _book
    
book:
  title: "BYU AI PM Bootcamp (2025)"
  favicon: images/prototyping-favicon.png
  author: "Scott Murff"
  date: "11/11/2025"
  chapters:
    - part: Overview
      chapters:
        - index.qmd
        - 00-computer-set.qmd
    - part: Topics
      chapters:
        - 01-vibe-coding.qmd
        - 04-spec-driven-development.qmd
        - 03-git-deployment.qmd
        #- 03-product-architecture.qmd
        - 05-power-users.qmd
        # - 02-first-prototype.qmd
    - part: Resources
      chapters:
    # Resources and Appendices
      - 99-prompts.qmd
      - 97-thought-leaders.qmd
      - 95-eng-checklist.qmd
      - 96-code-base-review.qmd
      - 98-tools.qmd
      # - 99-further-reading.qmd


bibliography: references.bib
csl: informs.csl

format:
  html:
    include-in-header: _header.html
    include-after-body: _footer.html
    theme: cosmo
    #link-external-icon: true
    link-external-newwindow: true
    css: styles.css
    toc: true
    number-sections: false
execute:
  eval: false
    
toc-title: On this page
